### PR TITLE
(WIP) Run tests against Kinto master

### PR DESCRIPTION
**Pull request by leplatrem**

### CODE REVIEW

**Comment by Natim** [comment]
Thansk @leplatrem

**Comment by almet** [comment]
Great :)

**Comment by leplatrem** [comment]
I realize that it does not work as expected : 
capture d ecran de 2016-03-09 10-47-57

I'll see if we can trigger two tasks (functional stable and development) instead of one.

**Comment by Natim** [comment]
I fixed it since see: https://travis-ci.org/Kinto/kinto-signer

**Pull request merged**
