### PR TITLE
Make sure the signature padding is correct.

### PR DESCRIPTION
**Pull request by Natim**
r? @almet

### CODE REVIEW

**Comment by almet** [comment]
Hmm, something is wrong with this pull request: it is not based on current master and does have some chars that shouldn't be present here. Can you rebase and fix this? thanks.

**Comment by Natim** [comment]
Yes I will do that as soon as I've got a minute :+1:

**Comment by Natim** [comment]
Updated.

**Comment by Natim** [comment]
Apparently this pull request doesn't solve the problem.
As we didn't had any problem so far, I would just close it and reopen if we see that some signature decoding fails.

**Comment by almet** [comment]
We still need to have a way to solve this padding issue in case it happens, so I opened #36 about it.

**Comment by Natim** [comment]
> We still need to have a way to solve this padding issue in case it happens, so I opened #36 about it.

We didn't add any issue in the functional tests yet while my PR added an issue so I think we are good.

**Pull request closed without merging**
